"""add storage path

Revision ID: b4d3f7afca78
Revises: 7a6d1f89bceb
Create Date: 2026-07-30 14:03:22.013814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d3f7afca78'
down_revision: Union[str, Sequence[str], None] = '7a6d1f89bceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('storage_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'storage_path')
    # ### end Alembic commands ###
